<!DOCTYPE html>
<html hreflang="en">
<head>
  <!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
  <script type="application/ld+json">
				{
				   "@context" : "http://schema.org",
				   "@type" : "Hospital",
				   "name": "Dr. Arun Saroha: Best Neurosurgeon in India ",  
				   "address": {
					"@type": "PostalAddress",
					"addressLocality": "Haryana,India",
					"addressRegion": "Gurugram",
					"postalCode": " 122001",
					"streetAddress": "Max Super Speciality Hospital, Saket Max Super Speciality Hospital"
				 },
				"image" : "https://drarunsaroha.com/assets/img/web-3-min.png",
				"telephone": "+917860000705",
				"url": "https://drarunsaroha.com/",
				"openingHours" : ["Mo-Su 00:00-23:59"],
			"aggregateRating" : {
   "@type" : "AggregateRating",
   "ratingValue" : "4.8",
    "bestRating" : "5",
    "worstRating" : "1",
    "ratingCount" : "255"
        }
			}
			</script>
 
  <!--<script type="application/ld+json">-->
  <!--{-->
  <!--  "@context" : "http://schema.org",-->
  <!--  "@type" : "LocalBusiness",-->
  <!--  "name" : "Dr. Arun Saroha",-->
  <!--  "image" : "https://drarunsaroha.com/assets/img/web-3-min.png",-->
  <!--  "description" : "With more than 20 successful years of experience in the field of Neurosurgery, Dr. Arun Saroha is an expert in treating brain & spine disorders and is the best neurosurgeon in the world.",-->
  <!--  "telephone" : "917860000705",-->
  <!--  "email" : "query@drarunsaroha.com",-->
  <!--  "address" : {-->
  <!--    "@type" : "PostalAddress",-->
  <!--    "addressLocality" : "Max Super Speciality Hospital, Saket Max Super Speciality Hospital, Gurugram"-->
  <!--  },-->
  <!--  "url" : "https://drarunsaroha.com/",-->
  <!--  "aggregateRating" : {-->
  <!--    "@type" : "AggregateRating",-->
  <!--    "ratingValue" : "4.8",-->
  <!--    "bestRating" : "5",-->
  <!--    "worstRating" : "1",-->
  <!--    "ratingCount" : "255"-->
  <!--  }-->
  <!--}-->
  <!--</script>-->
  
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Dr. Arun Saroha: Best Neurosurgeon & Spine Surgeon in India |</title>
  <meta name="description"
    content="Dr. Arun Saroha is the most trusted & recommended neurosurgeon & spine surgeon in India who specializes in brain and spine procedures. Schedule an appointment with him if you are searching for the best neurosurgeon in India. ">
    <meta name="keywords" content="top spine surgeon in gurgaon, spine surgeon gurgaon, best neurosurgeon in max hospital, best spine surgeon in max hospital, Best Neurosurgeon in Delhi, Best Spine Surgeon in Delhi, Top Neurosurgeon in Delhi, neurosurgeon in max gurgaon, best neurosurgeon in gurgaon, Neurosurgeon in gurgaon, Best Neuro Surgeon in Gurugram India, best spine surgeon in delhi, spine surgery New delhi, Best Spine Surgeon in New Delhi India, Top Spine Surgeon In Delhi, best spine surgeon in gurgaon, Best Spine Surgeon in Gurugram, Best Spine Doctor in gurgaon India ">
  <link rel="canonical" href="https://drarunsaroha.com/" />
  
  <script defer src="https://app.wacrs.com/install-widget/bundle.js?key=183b7c9c-f8d7-49ed-ba86-410e4f4b5676"></script>
  
       <noindex><script src="//widget.callbacktracker.com/tracker/261e2e9c39e726317bf6a879836d0127b4161751" charset="UTF-8"  async="async" type="text/javascript"></script></noindex>
  
  
  <meta name="google-site-verification" content="OM26BfidiQDn4kfujdxbwcW7ehdyVH21Vde0FlApwts" />
  <meta name="p:domain_verify" content="d766cdb9e7ac876cdea20ab8491e5e83"/>
  <!--start-header-->
  <style>
       @media only screen and (max-width: 768px) {
           .desk{
                display:none;
                }
            }
       @media only screen and (min-width: 768px) {
            .mob{display:none;}
           
    }
        
        .service-front img{
           width:100px;
           height:100px;
        }
        
  </style>
  
  <style>
    .hero .hero-headline {
    color: #444444;
    font-size: 52px;
    font-weight: 500;
    line-height: 75px;
    margin-bottom: 35px;
    margin-top: -428px;
}

.hero .hero-bio {
    font-size: 20px;
    font-weight: 400;
    line-height: 30px;
    margin-bottom: 30px;
    color: #999999;
}

.hero-action .btn {
    width: 300px;
    background-color: #183885;
    color: #ffffff;
    border-color: #183885;
    height: 60px;
    line-height: 48px;
    display: inline-block;
    font-weight: bold;
    text-align: center;
    justify-content:center;
    vertical-align: middle;
    cursor: pointer;
}

.typed-text {
            font-size: 52px;
            color: #444444;
            height: 60px;
            margin-bottom: 30px;
        }
        
@media (min-width: 425px) and (max-width: 1024px) {
  .hero .hero-headline{
      margin-top: -330px;
      font-size: 44px;
      line-height: 50px;
  }
  .typed-text {
            font-size: 44px;
            
        }
  .hero .hero-bio {
    
    margin-bottom: 25px;
  }      

  
}
  </style>
  
 
    
    
        <link href="assets/css/bootstrap.min.css" rel="preload" as="style" onload="this.onload=null;this.rel='stylesheet'">
        <noscript><link rel="stylesheet" href="assets/css/bootstrap.min.css"></noscript>
        
        <!-- Owl Carousel CSS -->
        <!--<link rel="stylesheet" href="assets/css/owl.carousel.min.css">-->
        <link href="assets/css/owl.carousel.min.css" rel="preload" as="style" onload="this.onload=null;this.rel='stylesheet'">
        <noscript><link rel="stylesheet" href="assets/css/owl.carousel.min.css"></noscript>
        
        <!--<link rel="stylesheet" href="assets/css/owl.theme.default.min.css">-->
        <link href="assets/css/owl.theme.default.min.css" rel="preload" as="style" onload="this.onload=null;this.rel='stylesheet'">
        <noscript><link rel="stylesheet" href="assets/css/owl.theme.default.min.css"></noscript>
        
        
        <!-- Meanmenu CSS -->
        <!--<link rel="stylesheet" href="assets/css/meanmenu.css">-->
        <link href="assets/css/meanmenu.css" rel="preload" as="style" onload="this.onload=null;this.rel='stylesheet'">
        <noscript><link rel="stylesheet" href="assets/css/meanmenu.css"></noscript>
        
        <!-- Icofonts CSS -->
        <!--<link rel="stylesheet" href="assets/css/icofont.min.css">-->
        <link href="assets/css/icofont.min.css" rel="preload" as="style" onload="this.onload=null;this.rel='stylesheet'">
        <noscript><link rel="stylesheet" href="assets/css/icofont.min.css"></noscript>
        
        <!-- Slick Slider CSS -->
        <!--<link rel="stylesheet" href="assets/css/slick.min.css">-->
        <!--<link href="assets/css/slick.min.css" rel="preload" as="style" onload="this.onload=null;this.rel='stylesheet'">-->
        <!--<noscript><link rel="stylesheet" href="assets/css/slick.min.css"></noscript>-->
        <!--<link rel="stylesheet" href="assets/css/slick-theme.css">-->
        
        <!-- Magnific Popup -->
        <!--<link rel="stylesheet" href="assets/css/magnific-popup.css">-->
        <link href="assets/css/magnific-popup.css" rel="preload" as="style" onload="this.onload=null;this.rel='stylesheet'">
        <noscript><link rel="stylesheet" href="assets/css/magnific-popup.css"></noscript>
        
        <!-- Wow CSS -->
        <!--<link rel="stylesheet" href="assets/css/animate.css">-->
        <link rel="stylesheet" href="assets/css/main.css">
        
        <!-- Style CSS -->
        <!--<link rel="stylesheet" href="assets/css/styleeeee.css">-->
        <link href="assets/css/style8.min.css" rel="preload" as="style" onload="this.onload=null;this.rel='stylesheet'">
        <noscript><link rel="stylesheet" href="assets/css/style8.min.css"></noscript>
        
        <!-- Responsive CSS -->
        <!--<link rel="stylesheet" href="assets/css/responsive.css">-->
        <link href="assets/css/responsive9.css" rel="preload" as="style" onload="this.onload=null;this.rel='stylesheet'">
        <noscript><link rel="stylesheet" href="assets/css/responsive9.css"></noscript>
    
        
        <link href="assets/css/mobil2.css" rel="preload" as="style" onload="this.onload=null;this.rel='stylesheet'">
        <noscript><link rel="stylesheet" href="assets/css/mobil2.css"></noscript>
        
        <link rel="icon" type="image/png" href="https://drarunsaroha.com/assets/img/fav icon.png" defer>
        
        <script src="assets/js/jquery.min.js"></script>
        
       <!--  Google Tag Manager -->
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-N7KGH72');</script>
<!-- End Google Tag Manager -->
    
    <style>
        @media only screen and (max-width: 991px) {
                .main-nav {
                    display: block !important;
                }
            }
            
        .emergency-area {
            margin-top: 60px !important;
        }
    </style>
        
    </head>
    <body>
        <!-- Header Top -->
        <div class="header-top">
            <div class="container">
                <div class="d-flex flex-row align-items-center">
                    <div class="col-sm-9 col-lg-9 col-md-9">
                        <div class="header-top-item">
                            <div class="header-top-left">
                                <ul>
                                    <li>
                                        <a href="tel:+919818778811">
                                           <img src="assets/img/calli.webp" alt="best neurosurgeon in the world"> 
                                             +91 9818778811,
                                        </a>
                                        <a href="tel:+919990778811">
                                           <!--<img src="assets/img/calli.png" alt="best neurosurgeon in the world"> -->
                                            +91 9990778811
                                        </a>
                                    </li>
                                    <!--<li>-->
                                    <!--    <a href="mailto:hello@medsev.com">-->
                                    <!--        <i class="icofont-ui-message"></i>-->
                                    <!--        hello@medsev.com-->
                                    <!--    </a>-->
                                    <!--</li>-->
                                    <!--<li>-->
                                    <!--    <i class="icofont-location-pin"></i>-->
                                    <!--    210-27 Quadra, Canada -->
                                    <!--</li>-->
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-3 col-lg-3 col-md-3">
                        <div class="header-top-item">
                            <div class="header-top-right">
                                <ul>
                                    <li>
                                        <a href="tel:+91 9810778811">
                                           <img src="assets/img/ambica.png" alt="best neurosurgeon in the world">
                                        </a>
                                    </li>
                                    <li>
                                        <a href="tel:+91 9810778811">
                                            <img src="assets/img/emnre.webp" alt="best neurosurgeon in the world">
                                        </a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- End Header Top -->
        
        <!-- Start Navbar Area -->
        <div class="navbar-area sticky-top">
            <!-- Menu For Mobile Device -->
            <div class="mobile-nav">
                <a href="index.php" class="logo">
                    <img src="assets/img/sbi-mobile-logo.png" alt="best neurosurgeon in delhi">
                </a>
            </div>

            <!-- Menu For Desktop Device -->
            <div class="main-nav">
                <div class="container-fluid">
                    <nav class="navbar navbar-expand-md navbar-light">
                        <a class="navbar-brand" href="https://drarunsaroha.com">
                            <img src="assets/img/sbi-log.png" alt="best neurosurgeon in delhi"  style="width:150px">
                        </a>
                        <div class="collapse navbar-collapse mean-menu" id="navbarSupportedContent">
                            <ul class="navbar-nav">
                                
                                <li class="nav-item">
                                    <a href="https://drarunsaroha.com/about/" class="nav-link">Dr. Arun Saroha</a>
                                </li>
                                <li class="nav-item">
                                    <a href="#" class="nav-link dropdown-toggle"> Spine Procedures </a>
                                    <ul class="dropdown-menu">
                                        <li class="nav-item">
                                            <a href="https://drarunsaroha.com/back-pain-treatment-in-india/" class="nav-link">Back Pain Treatment</a>
                                        </li>
                                        <li class="nav-item">
                                            <a href="https://drarunsaroha.com/best-treatment-cervical-spondylosis-in-India/" class="nav-link">Cervical Spondylosis Treatment</a>
                                        </li>
                                        <li class="nav-item">
                                            <a href="https://drarunsaroha.com/cervical-spine-surgery-in-India/" class="nav-link">Cervical Spine Surgery</a>
                                        </li>
                                        <li class="nav-item">
                                            <a href="https://drarunsaroha.com/degenerative-disc-disease-treatment-in-India/" class="nav-link">Degenerative Disc Disease</a>
                                        </li>
                                        <li class="nav-item">
                                            <a href="https://drarunsaroha.com/disc-replacement-surgery-in-India/" class="nav-link">Disc Replacement Surgery</a>
                                        </li>
                                        <li class="nav-item">
                                            <a href="https://drarunsaroha.com/herniated-disc-surgery-in-india" class="nav-link">Herniated Disc Surgery or Slip Disc Surgery</a>
                                        </li>
                                        <li class="nav-item">
                                            <a href="https://drarunsaroha.com/scoliosis-treatment-in-India/" class="nav-link">Scoliosis Treatment</a>
                                        </li>
                                        <li class="nav-item">
                                            <a href="https://drarunsaroha.com/spinal-stenosis-surgery-in-India/" class="nav-link">Spinal Stenosis Surgery</a>
                                        </li>
                                    </ul>
                                </li>
                                <li class="nav-item">
                                    <a href="#" class="nav-link dropdown-toggle">Brain Procedures</a>
                                    <ul class="dropdown-menu">
                                        <li class="nav-item">
                                            <a href="https://drarunsaroha.com/blood-clot-brain-treatment-in-India/" class="nav-link">Blood Clot Brain Treatment</a>
                                        </li>
                                        <li class="nav-item">
                                            <a href="https://drarunsaroha.com/brain-aneurysm-treatment-in-India/" class="nav-link">Brain Aneurysm Treatment</a>
                                        </li>
                                        <li class="nav-item">
                                            <a href="https://drarunsaroha.com/brain-surgery-in-India/" class="nav-link">Brain Surgery</a>
                                        </li>
                                        <li class="nav-item">
                                            <a href="https://drarunsaroha.com/brain-tumor-surgery-in-india/" class="nav-link">Brаіn Tumоr Surgery</a>
                                        </li>
                                        <li class="nav-item">
                                            <a href="https://drarunsaroha.com/best-headache-treatment-in-India/" class="nav-link">Best Headache treatment</a>
                                        </li>
                                    </ul>
                                </li>
                                <li class="nav-item">
                                    <a href="https://drarunsaroha.com/international.php" class="nav-link">International Patients</a>
                                </li>
                                 <!--<ul class="dropdown-menu">
                                <li class="nav-item">
                                    <a href="#" class="nav-link dropdown-toggle">International Patients </a>
                                    <ul class="dropdown-menu">
                                        <li class="nav-item">
                                            <a href="doctor.html" class="nav-link">Doctor</a>
                                        </li>
                                        <li class="nav-item">
                                            <a href="doctor-details.html" class="nav-link">Doctor Details</a>
                                        </li>
                                    </ul>
                                </li>
                                -->
                                <li class="nav-item">
                                    <a href="https://drarunsaroha.com/blog/" class="nav-link ">Blog</a>
                                    <!--<ul class="dropdown-menu">-->
                                    <!--    <li class="nav-item">-->
                                    <!--        <a href="blog.html" class="nav-link">Blog</a>-->
                                    <!--    </li>-->
                                    <!--    <li class="nav-item">-->
                                    <!--        <a href="blog-details.html" class="nav-link">Blog Details</a>-->
                                    <!--    </li>-->
                                    <!--</ul>-->
                                </li>
                                <li class="nav-item">
                                    <a href="https://drarunsaroha.com/contact/" class="nav-link">Contact Us</a>
                                </li>
                            </ul>
                            
                        </div>
                    </nav>
                </div>
            </div>
        </div>
        
        <div class="whatsapp" id="whatsapp" style="
    curson:pointer;
    bottom: -10px !important;
    float: unset;
    height: auto;
    width: 10rem;
    box-shadow: none !important;
    left: 20px !important;
    background-color: transparent !important;
    animation-name: purechat-bounceInUp !important;
    cursor: default !important;
    position: fixed !important;
    z-index: 2147483646 !important;
    transform: none !important;
    ">
        <a href="https://wa.me/+919818778811?text=Hello Dr. Arun Saroha, I have Brain problem, Please give appointment for online consultation. Thank you" target="_blank" rel="noopener noreferrer">
            <img class="purechat-collapsed-image" width="100%" src="assets/img/whatsapp-min.webp"></a>
    </div>
  
  
  
  <!----End--header----->
  <!-- Home Slider -->
  <div class="home-slider home-slider-two owl-theme owl-carousel" style="margin-top:200px">
    <div class="slider-item slider-item-img-two">
      <div class="d-table">
        <div class="d-table-cell">
          <div class="container">
            <div class="slider-text">
              <div class="slider-shape">
                <!--<img loading="lazy" src="assets/img/home-one/5.png" alt="best neurosurgeon in the world">-->
              </div>
              <h2 class="ab" style="font-size: 45px; color:#000000">Avail the benefits<br> of minimally invasive
                Spinal<br> and Brain Surgeries </h2>
              <p class="ab">Consult the most trusted & recommended neurosurgeon in India.
                Get the best & highest quality and state-of-art medical and surgical care.
              </p>
              <div class="common-btn ab">
                <a href="https://drarunsaroha.com/contact/">Get Appointment</a>
              </div>
            </div>
            <div class="slider-shape">
                <img loading="lazy" src="assets/img/home-one/5.png" alt="best neurosurgeon in the world">
              </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  
  <section id="hero" class="section hero">
        <div class="bg-section">
          <img src="assets/img/banner-min.jpg" alt="spine surgery Gurgaon">
        </div>
        <div class="container">
          <div class="row row-content">
            <div class="col-12 col-md-6 col-lg-6">
              <div class="hero-headline">Your Health Care is
                Our
              <div class="typed-text" id="typed-text"></div>
              <div class="hero-bio">We work to take care of your health and body.</div>
              <div class="hero-action">
                  <a href="https://drarunsaroha.com/contact.php" class="btn btn--primary">Book an Appointment now!!</a>
              
              
              </div>
            </div>
            <div class="col-12 col-md-6 col-lg-6"></div>
          </div>
          <!-- .row end -->
        </div>
        <!-- .container end -->
      </section>
      
   
  
  <!-- Emergency -->
  <div class="emergency-area">
    <div class="container">
      <div class="row emergency-bg">
        <div class="col-sm-6 col-lg-4">
          <div class="emergency-item">
            <i class="icofont-ui-call"></i>
            <div class="emergency-inner">
              <h3>Emergency Call</h3>
              <!--<p>+91 7860 0007 05</p>-->
              <!--<p>+91 7860 0007 05</p>-->
              <p>+91 9810778811</p>
            </div>
          </div>
          <div class="emergency-item">
            <i class="icofont-ui-call"></i>
            <div class="emergency-inner">
              <h3>Online Consultation</h3>
              <!--<p>+91 7860 0007 05</p>-->
              <!--<p>+91 7860 0007 05</p>-->
              <p>+91 9990778811</p>
            </div>
          </div>
        </div>
        <div class="col-sm-6 col-lg-4">
          <div class="emergency-item">
            <i class="icofont-location-pin"></i>
            <div class="emergency-inner">
              <h3>Location</h3>
              <!--<p>Max Super Speciality Hospital, Saket and Gurugram</p>-->
              <p>Max Hospital, Director & Unit Head of Spine and Neurosurgery
                B Block, Sushant Lok 1, Near Huda City Centre
                Gurugram- 122001
              </p>
            </div>
          </div>
        </div>
        <div class="col-sm-6 col-lg-4">
          <div class="emergency-item">
            <i class="icofont-location-pin"></i>
            <div class="emergency-inner">
              <h3>Location</h3>
              <!--<p>Max Super Speciality Hospital, Saket and Gurugram</p>-->
              <p>Max Super Speciality Hospital, Department of Spine and Neurosurgery
                West Block, Ground Floor, Room No. 7
                Saket, New Delhi- 110017
              </p>
            </div>
          </div>
        </div>
        <!--<div class="col-sm-6 offset-sm-3 offset-lg-0 col-lg-4">-->
        <!--    <div class="emergency-item">-->
        <!--        <i class="icofont-ambulance-crescent"></i>-->
        <!--        <div class="emergency-inner">-->
        <!--            <h3>Ambulance</h3>-->
        <!--            <p>+91 7860 0007 05</p>-->
        <!--            <p>+91 7860 0007 05</p>-->
        <!--        </div>-->
        <!--    </div>-->
        <!--</div>-->
      </div>
    </div>
  </div>
  <!-- End Emergency -->
  <!-- Welcome -->
  <section class="welcome-area ptb-100">
    <div class="container-fluid p-0">
      <div class="row m-0">
        <div class="col-lg-6 p-0">
          <div class="welcome-item welcome-left">
            <img loading="lazy" src="assets/img/saroha-min.webp" alt="image">
          </div>
        </div>
        <div class="col-lg-6 p-0">
          <div class="welcome-item welcome-right">
            <div class="section-title-two">
              <span>About Doctor</span>
              <h1>Dr. Arun Saroha: Best Neurosurgeon & Spine Surgeon in India </h1>
            </div>
            <p class="aboutPara">Dr. Arun Saroha is the Best Neurosurgeon & Spine Surgeon in Max Hospital, India who specializes in brain and spine
              procedures. He has more than 25 years of experience and has performed over 6,000 successful spinal and
              brain procedures. Spine surgery, neuro-oncology, neurotrauma, scoliosis surgery, Stroke Cerebrovascular
              Surgery, Pediatric brain and spine surgery, minimally invasive spine surgery, brain tumor surgery, spine
              fixation, and fusion surgery are among his specialties.</p>
            <ul>
              <li class="wow fadeInUp" data-wow-delay=".3s">
                <div>
                    <i class="icofont-doctor-alt"></i>
                </div>
                <div class="welcome-inner">
                  <h3>Education and Training</h3>
                  <p>
                    MBBS from RNT Medical College, Udaipur, Rajasthan, India
                    MS (General Surgery) from RNT Medical College, Udaipur, Rajasthan, India
                    MCh (Neurosurgery) from PGI Chandigarh, India
                  </p>
                </div>
              </li>
              <li class="wow fadeInUp" data-wow-delay=".5s">
                <div>
                    <i class="icofont-stretcher"></i>
                </div>
                <div class="welcome-inner">
                  <h3>Emergency 24 hours</h3>
                  <p>Offer the most advanced and modern treatment of conditions of the brain and spine by experts.</p>
                </div>
              </li>
              <li class="wow fadeInUp" data-wow-delay=".7s">
                <div>
                    <i class="icofont-network"></i>
                </div>
                <div class="welcome-inner">
                  <h3>Modern Technology</h3>
                  <p>We are committed to providing the highest level of professional service and personalized care using
                    the most advanced medical technology applications.</p>
                </div>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </section>
  <!-- End Welcome -->
  <!-- Services -->
  <section class="services-area pb-70">
    <div class="container">
      <div class="section-title-two">
        <h2 style="text-align:center !important;">Services Offered</h2>
      </div>
      <div class="row">
        <div class="col-sm-6 col-lg-4 wow fadeInUp" data-wow-delay=".3s">
          <div>
            <div class="d-table">
              <div class="d-table-cell">
                <div class="service-front" style="text-align:center;">
                  <img loading="lazy" src="assets/img/Disc Herniation-01.svg" alt="best neurosurgeon in delhi">
                  <h3>Disc Herniation</h3>
                  <p>Dr. Arun is an expert spine surgeon in India who performs minimally invasive Keyhole surgery
                    for correcting disk herniated. </p>
                  <a href="https://drarunsaroha.com/herniated-disc-surgery-in-India.php">
                    Read More
                    <i class="icofont-long-arrow-right"></i>
                  </a>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="col-sm-6 col-lg-4 wow fadeInUp" data-wow-delay=".5s">
          <div>
            <div class="d-table">
              <div class="d-table-cell">
                <div class="service-front" style="text-align:center;">
                  <img loading="lazy" src="assets/img/SPONDYLOSIS-01-01.svg" alt="best neurosurgeon in the world">
                  <h3>Spondylosis</h3>
                  <p>Dr. Arun Saroha performs the laminectomy, discectomy, and corpectomy surgery to correct cervical
                    spondylosis or osteoarthritis.</p>
                  <a href="https://drarunsaroha.com/best-treatment-cervical-spondylosis-in-India/">
                    Read More
                    <i class="icofont-long-arrow-right"></i>
                  </a>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="col-sm-6 col-lg-4 wow fadeInUp" data-wow-delay=".7s">
          <div>
            <div class="d-table">
              <div class="d-table-cell">
                <div class="service-front" style="text-align:center;">
                  <img loading="lazy" src="assets/img/degenerative disc-01-01.svg" alt="best neurosurgeon in delhi">
                  <h3>Degenerative Disc</h3>
                  <p>Dr. Arun Saroha is an expert in performing traditional decompression surgeries from the back and
                    front of the spine.</p>
                  <a href="https://drarunsaroha.com/degenerative-disc-disease-treatment-in-India/">
                    Read More
                    <i class="icofont-long-arrow-right"></i>
                  </a>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="col-sm-6 col-lg-4 wow fadeInUp" data-wow-delay=".9s">
          <div>
            <div class="d-table">
              <div class="d-table-cell">
                <div class="service-front" style="text-align:center;">
                  <img loading="lazy" src="assets/img/brain tumar surgery.svg" alt="best neurosurgeon in the world">
                  <h3>Brain Tumor Surgery</h3>
                  <p>The best doctor in India for brain tumor, uses the state-of-the-art equipment at the facility that
                    makes the process of brain tumor removal easier.</p>
                  <a href="https://drarunsaroha.com/brаіn-tumоr-surgery-in-india/">
                    Read More
                    <i class="icofont-long-arrow-right"></i>
                  </a>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="col-sm-6 col-lg-4 wow fadeInUp" data-wow-delay=".3s">
          <div>
            <div class="d-table">
              <div class="d-table-cell">
                <div class="service-front" style="text-align:center;">
                  <img loading="lazy" src="assets/img/brain surgery-01.svg" alt="best neurosurgeon in delhi">
                  <h3>Brain Surgery</h3>
                  <p>Dr. Arun Saroha is an expert in performing a craniotomy,deep brain stimulation, and minimally
                    invasive endonasal endoscopic surgery.</p>
                  <a href="https://drarunsaroha.com/brain-surgery-in-India/">
                    Read More
                    <i class="icofont-long-arrow-right"></i>
                  </a>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="col-sm-6 col-lg-4 wow fadeInUp" data-wow-delay=".5s">
          <div>
            <div class="d-table">
              <div class="d-table-cell">
                <div class="service-front" style="text-align:center;">
                  <img loading="lazy" src="assets/img/headache treatment-01.svg" alt="best neurosurgeon in the world">
                  <h3>Headache Treatment</h3>
                  <p>Dr. Arun Saroha is an expert brain surgery doctor and provides treatment for primary, secondary,
                    cluster, rebound, and thunderclap headaches.</p>
                  <a href="https://drarunsaroha.com/best-headache-treatment-in-India/">
                    Read More
                    <i class="icofont-long-arrow-right"></i>
                  </a>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  <!-- End Services -->
  <!-- Speciality -->
  <section class="speciality-area pb-100">
    <div class="container-fluid p-0">
      <div class="row m-0">
        <div class="col-lg-7">
          <div class="speciality-left">
            <div class="section-title-two">
              <h2 style="text-align:center;">Why choose us?</h2>
            </div>
            <div class="speciality-item">
              <div class="row m-0">
                <div class="col-sm-6 col-lg-6 col-6 wow fadeInUp" data-wow-delay=".3s">
                  <div class="speciality-inner">
                    <i class="icofont-check-circled"></i>
                    <h3>Highest patient satisfactory rate.</h3>
                  </div>
                </div>
                <div class="col-sm-6 col-lg-6 col-6 wow fadeInUp" data-wow-delay=".5s">
                  <div class="speciality-inner">
                    <i class="icofont-check-circled"></i>
                    <h3>Safe and effective results.</h3>
                  </div>
                </div>
                <div class="col-sm-6 col-lg-6 col-6 wow fadeInUp" data-wow-delay=".3s">
                  <div class="speciality-inner">
                    <i class="icofont-check-circled"></i>
                    <h3>Patient safety priority.</h3>
                  </div>
                </div>
                <div class="col-sm-6 col-lg-6 col-6 wow fadeInUp" data-wow-delay=".5s">
                  <div class="speciality-inner">
                    <i class="icofont-check-circled"></i>
                    <h3>Sanitized rooms and fully equipped rooms.</h3>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="col-lg-5 pr-0">
          <div class="speciality-item speciality-right">
            <img loading="lazy" src="assets/img/sarunstes-min1.webp" alt="best neurosurgeon in the world">
            <!--   <div class="speciality-emergency">
                                <div class="speciality-icon">
                                    <i class="icofont-ui-call"></i>
                                </div>
                                <h3>Emergency Call</h3>
                                <p>+07 554 332 322</p>
                            </div> --->
          </div>
        </div>
      </div>
    </div>
  </section>
  <!-- End Speciality -->
  <div class="counter-area counter-area-two " style="background-color:#f8fbff;">
    <div class="container">
      <div class="row counter-bg">
        <div class="col-sm-6 col-lg-3 col-6">
          <div class="counter-item">
            <i class="icofont-patient-bed"></i>
            <h3 class="counter">850</h3>
            <p>Gold Standard Treatments</p>
          </div>
        </div>
        <div class="col-sm-6 col-lg-3 col-6">
          <div class="counter-item">
            <i class="icofont-people"></i>
            <h3><span class="counter">6,000</span>+</h3>
            <p>Brain and Spine surgeries performed successfully</p>
          </div>
        </div>
        <div class="col-sm-6 col-lg-3 col-6">
          <div class="counter-item">
            <i class="icofont-doctor-alt"></i>
            <h3 class="counter">100</h3>
            <p>Patient Satisfaction Rate</p>
          </div>
        </div>
        <div class="col-sm-6 col-lg-3 col-6">
          <div class="counter-item">
            <i class="icofont-badge"></i>
            <h3 class="counter">25</h3>
            <p>Years of Experience</p>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- End Blog -->
  <!-- Video -->
  <div class="video-wrap video-wrap-two">
    <div class="container-fluid p-0">
      <div class="tab-content" id="pills-tabContent">
        <div class="tab-pane fade show active" id="pills-home" role="tabpanel" aria-labelledby="pills-home-tab">
          <div class="video-area bra">
            <div class="d-table">
              <div class="d-table-cell">
                <div class="container">
                  <div class="video-item">
                    <a href="https://www.youtube.com/watch?v=50shqdODSmQ" target="_blank" class="popup-youtube">
                      <i class="icofont-ui-play"></i>
                    </a>
                    <div class="video-content">
                      <h3>Brain Tumour Surgery</h3>
                      <p>The patient who Dr. Arun Saroha After getting to know about his outstanding expertise in spine
                        and brain tumors The patient was unable to move his right side of the body and was in an
                        unconscious state when he reached us on performing the MRI it was diagnosed a widespread grade
                        II Tumor coming out of the skull. </p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="tab-pane fade" id="pills-profile" role="tabpanel" aria-labelledby="pills-profile-tab">
          <div class="video-area verte">
            <div class="d-table">
              <div class="d-table-cell">
                <div class="container">
                  <div class="video-item">
                    <a href="https://www.youtube.com/watch?v=oJTK69ZK4Nc" class="popup-youtube">
                      <i class="icofont-ui-play"></i>
                    </a>
                    <div class="video-content">
                      <h3>Vertebral metastasis</h3>
                      <p>A 60 years old woman from Sudan is an operated case of D11- D12 vertebral metastasis with
                        unknown primary post D9- L1 posterolateral fixation. She came to Dr. Arun Saroha best spine surgeon
                        in max hospital for her spine surgery. Today, she is living her life to the fullest with her family
                        thanks to her successful spine surgery!
                      </p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="tab-pane fade" id="pills-contact" role="tabpanel" aria-labelledby="pills-contact-tab">
          <div class="video-area heri">
            <div class="d-table">
              <div class="d-table-cell">
                <div class="container">
                  <div class="video-item">
                    <a href="https://www.youtube.com/watch?v=4DRPPrIKCrc" class="popup-youtube">
                      <i class="icofont-ui-play"></i>
                    </a>
                    <div class="video-content">
                      <h3>Herniated Disc </h3>
                      <p>Sher Mohammad has been a herniated disc patient for 25 years of his life. After trying every
                        possible doctor, he finally decided to visit Dr Arun Saroha best neurosurgeon in max hospital,
                        Saket, Delhi. In the video, he talks about his experience with Dr Saroha.</p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="tab-pane fade" id="pills-icu" role="tabpanel" aria-labelledby="pills-icu-tab">
          <div class="video-area micro">
            <div class="d-table">
              <div class="d-table-cell">
                <div class="container">
                  <div class="video-item">
                    <a href="https://www.youtube.com/watch?v=6XJXXva_AD8" class="popup-youtube">
                      <i class="icofont-ui-play"></i>
                    </a>
                    <div class="video-content">
                      <h3>Microscopic Spine Surgery </h3>
                      <p>Mrs. Nada Nasrula from Iraq came to us with severe pain in the neck and back not knowing what
                        exactly was wrong with her until she consulted Dr. Arun Saroha – Director of Neurosurgery, Max
                        Hospital. </p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="tab-pane fade" id="pills-doctor" role="tabpanel" aria-labelledby="pills-doctor-tab">
          <div class="video-area brach">
            <div class="d-table">
              <div class="d-table-cell">
                <div class="container">
                  <div class="video-item">
                    <a href="https://www.youtube.com/watch?v=UAB79mar3xI" class="popup-youtube">
                      <i class="icofont-ui-play"></i>
                    </a>
                    <div class="video-content">
                      <h3>Brachial plexus injury</h3>
                      <p>Meet a Happy Patient from Kenya, Mr. Kennedy Omondi. He had an accident in 2018 where his left
                        arm got paralyzed. He was diagnosed with left brachial plexus injury- nerve root avulsion. </p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="container">
      <ul class="video-nav nav nav-pills" id="pills-tab" role="tablist">
        <li class="nav-item video-nav-item">
          <a class="nav-link active" id="pills-home-tab" data-toggle="pill" href="#pills-home" role="tab"
            aria-controls="pills-home" aria-selected="true">Brain Tumour Surgery</a>
        </li>
        <li class="nav-item video-nav-item">
          <a class="nav-link" id="pills-profile-tab" data-toggle="pill" href="#pills-profile" role="tab"
            aria-controls="pills-profile" aria-selected="false">vertebral metastasis</a>
        </li>
        <li class="nav-item video-nav-item">
          <a class="nav-link" id="pills-contact-tab" data-toggle="pill" href="#pills-contact" role="tab"
            aria-controls="pills-contact" aria-selected="false">Herniated Disc</a>
        </li>
        <li class="nav-item video-nav-item">
          <a class="nav-link" id="pills-icu-tab" data-toggle="pill" href="#pills-icu" role="tab"
            aria-controls="pills-icu" aria-selected="false">Microscopic Spine Surgery</a>
        </li>
        <li class="nav-item video-nav-item">
          <a class="nav-link" id="pills-doctor-tab" data-toggle="pill" href="#pills-doctor" role="tab"
            aria-controls="pills-doctor" aria-selected="false">brachial plexus injury</a>
        </li>
      </ul>
    </div>
  </div>
  <!-- End Video -->
  <!--<section class="doctors-area pt-100">
            <div class="container">
                <div class="section-title-two">
                    <span>Doctors</span>
                    <h2>Meet Our Doctors </h2>
                </div>
                <div class="row">
                    <div class="col-sm-6 col-lg-4 wow fadeInUp" data-wow-delay=".3s">
                        <div class="doctor-item">
                            <div class="doctor-top">
                                <img loading="lazy" src="assets/img/home-one/doctor/1.jpg" alt="Doctor">
                                <a href="appointment.html">Get Appointment</a>
                            </div>
                            <div class="doctor-bottom">
                                <h3>
                                    <a href="doctor-details.html">Dr. Babatunde</a>
                                </h3>
                                <span>Neurosurgeon</span>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-6 col-lg-4 wow fadeInUp" data-wow-delay=".5s">
                        <div class="doctor-item">
                            <div class="doctor-top">
                                <img loading="lazy" src="assets/img/home-one/doctor/2.jpg" alt="Doctor">
                                <a href="appointment.html">Get Appointment</a>
                            </div>
                            <div class="doctor-bottom">
                                <h3>
                                    <a href="doctor-details.html">Dr. Addision Smith</a>
                                </h3>
                                <span>Neurosurgeon</span>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-6 offset-sm-3 offset-lg-0 col-lg-4 wow fadeInUp" data-wow-delay=".7s">
                        <div class="doctor-item">
                            <div class="doctor-top">
                                <img loading="lazy" src="assets/img/home-one/doctor/3.jpg" alt="Doctor">
                                <a href="appointment.html">Get Appointment</a>
                            </div>
                            <div class="doctor-bottom">
                                <h3>
                                    <a href="doctor-details.html">Dr. Sarah Tylor</a>
                                </h3>
                                <span>Dental Surgeon</span>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="doctor-btn">
                    <a href="doctor.html">See All</a>
                </div>
            </div>
        </section>
        <!-- End Doctors -->
  <!-- Counter -->
  <!-- End Counter -->
  <!-- <section class="appointment-area pb-100">
            <div class="container-fluid p-0">
                <div class="appointment-item">
                    <h2>Book your appointment</h2>
                    <span>We will confirm your  appointment within 2 hours</span>
                    <div class="appointment-form">
                        <form>
                            <div class="row">
                                <div class="col-lg-6">
                                    <div class="form-group">
                                        <i class="icofont-business-man-alt-1"></i>
                                        <label>Name</label>
                                        <input type="text" class="form-control" placeholder="Enter Your Name">
                                    </div>
                                </div>
                                <div class="col-lg-6">
                                    <div class="form-group">
                                        <i class="icofont-ui-message"></i>
                                        <label>Email</label>
                                        <input type="email" class="form-control" placeholder="Enter Your Email">
                                    </div>
                                </div>
                                <div class="col-lg-6">
                                    <div class="form-group">
                                        <i class="icofont-ui-call"></i>
                                        <label>Phone</label>
                                        <input type="text" class="form-control" placeholder="Enter Your Number">
                                    </div>
                                </div>
                                <div class="col-lg-6">
                                    <div class="form-group">
                                        <i class="icofont-hospital"></i>
                                        <label>Services</label>
                                        <select class="form-control" id="exampleFormControlSelect1">
                                            <option>Dental Care</option>
                                            <option>Neurology</option>
                                            <option>Cardiology</option>
                                            <option>Pathology</option>
                                        </select>
                                    </div>
                                </div>
                                
                            </div>
                            <div class="text-center">
                                <button type="submit" class="btn appointment-btn">Submit</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </section>
        <!-- End Appointment -->
  <!-- Blog -->
  <!--<div id="wid_1670317434062" style="margin-top:20px;"></div> <script defer>    sc = document.createElement("script");    sc.setAttribute("defer",true);    sc.setAttribute("src","https://dbwx2z9xa7qt9.cloudfront.net/bundle.js?cachebust=1670317434062");    sc.setAttribute("theme","light");    sc.setAttribute("footer", true);    sc.setAttribute("widget-type","carousel");    sc.setAttribute("token","637cb6e2990df255481e500a");    sc.setAttribute('apiurl', "https://server.recensioni.io/api/v0.0.9");    sc.setAttribute('stats',"true");    sc.setAttribute('addReview',"true");    sc.setAttribute('profile-pic',"true");    sc.setAttribute('review-name',"true");    sc.setAttribute('wl', "false");    sc.setAttribute('wlndig', "https://go.climbo.com/dr.-arun-saroha");    document.getElementById("wid_1670317434062").appendChild(sc);</script>-->
  <section class="pt-100 pb-70">
    <div class="container">
      <div class="section-title-two">
        <h2 style="text-align:center;">Our Latest Blogs</h2>
      </div>
      <div class="row">
          <div class="col-sm-6 col-lg-4 wow fadeInUp" data-wow-delay=".5s">
          <div class="blog-item">
            <div class="blog-top">
              <a href="https://drarunsaroha.com/blog/?qb-b=how-to-know-if-you-need-spine-surgery">
                <img loading="lazy" src="https://media.quickblog.co/images/uploadsthumb/4734/164097f006b8354e45f9ad4abc8d51e6_how%20to%20know.jpg" alt="best neurosurgeon in delhi">
              </a>
            </div>
            <div class="blog-bottom">
              <h3>
                <a href="https://drarunsaroha.com/blog/?qb-b=how-to-know-if-you-need-spine-surgery">How to know if you need spine surgery</a>
              </h3>
              <p>About 60% of the adult population suffers from back pain at some point in their life. Back pain is caused by many factors like...</p>
              <ul>
                <li>
                  <a href="https://drarunsaroha.com/blog/?qb-b=how-to-know-if-you-need-spine-surgery">
                    Read More
                    <i class="icofont-long-arrow-right"></i>
                  </a>
                </li>
                <li>
                  <i class="icofont-calendar"></i>
                  Nov 20, 2022
                </li>
              </ul>
            </div>
          </div>
        </div>
        
        <div class="col-sm-6 col-lg-4 wow fadeInUp" data-wow-delay=".3s">
          <div class="blog-item">
            <div class="blog-top">
              <a href="https://drarunsaroha.com/blog/?qb-b=five-things-you-should-know-about-brain-tumours">
                <img loading="lazy" src="https://media.quickblog.co/images/uploadsthumb/4734/8419d61c988b9e571a826b40f113feec_Five%20things%20you%20should%20know%20about%20brain%20tumours.jpg" alt="best neurosurgeon in the world">
              </a>
            </div>
            <div class="blog-bottom">
              <h3>
                <a href="https://drarunsaroha.com/blog/?qb-b=five-things-you-should-know-about-brain-tumours">Five things you should know about brain tumours</a>
              </h3>
              <p>Brain tumour diagnosis can be a nightmare for most of us. Since our bodily functions depend on our brains... </p>
              <ul>
                <li>
                  <a href="https://drarunsaroha.com/blog/?qb-b=five-things-you-should-know-about-brain-tumours">
                    Read More
                    <i class="icofont-long-arrow-right"></i>
                  </a>
                </li>
                <li>
                  <i class="icofont-calendar"></i>
                  Nov 13, 2022
                </li>
              </ul>
            </div>
          </div>
        </div>
        
        <div class="col-sm-6 offset-sm-3 offset-lg-0 col-lg-4 wow fadeInUp" data-wow-delay=".7s">
          <div class="blog-item">
            <div class="blog-top">
              <a href="https://drarunsaroha.com/blog/?qb-b=brain-tumour-3-common-myths-about-brain-tumours-debunked">
                <img loading="lazy" src="https://media.quickblog.co/images/uploadsthumb/2453/5c3d11551b69a351d922a0a3db3271c2_b.jpg" alt="best neurosurgeon in delhi">
              </a>
            </div>
            <div class="blog-bottom">
              <h3>
                <a href="https://drarunsaroha.com/blog/?qb-b=brain-tumour-3-common-myths-about-brain-tumours-debunked">Brain tumour: 3 common myths about brain tumours debunked</a>
              </h3>
              <p>The brain is the centre of our nervous system. It controls many bodily functions and helps us to lead our life...</p>
              <ul>
                <li>
                  <a href="https://drarunsaroha.com/blog/?qb-b=brain-tumour-3-common-myths-about-brain-tumours-debunked">
                    Read More
                    <i class="icofont-long-arrow-right"></i>
                  </a>
                </li>
                <li>
                  <i class="icofont-calendar"></i>
                  Nov 10, 2022
                </li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  
  <script>
        const phrases = [
            "Responsibility",
            "Purpose",
            "Ambition"
        ];
        
        const typedTextElement = document.getElementById('typed-text');
        let phraseIndex = 0;
        let charIndex = 0;
        let isDeleting = false;

        function typeText() {
            const currentPhrase = phrases[phraseIndex];
            
            if (isDeleting) {
                typedTextElement.textContent = currentPhrase.substring(0, charIndex - 1);
                charIndex--;
            } else {
                typedTextElement.textContent = currentPhrase.substring(0, charIndex + 1);
                charIndex++;
            }

            if (!isDeleting && charIndex === currentPhrase.length) {
                setTimeout(() => isDeleting = true, 1000);
            } else if (isDeleting && charIndex === 0) {
                isDeleting = false;
                phraseIndex = (phraseIndex + 1) % phrases.length;
            }

            setTimeout(typeText, isDeleting ? 50 : 100);
        }

        typeText();
    </script>
    
</body>
  <?php include 'footer.php';?>