
<!DOCTYPE html>
<html hreflang="en">
    <head>
        <!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
         <script type="application/ld+json">
				{
				   "@context" : "http://schema.org",
				   "@type" : "Hospital",
				   "name": "best neurosurgeon in delhi, best neurosurgeon in the world",  
				   "address": {
					"@type": "PostalAddress",
					"addressLocality": "Haryana,India",
					"addressRegion": "Gurugram",
					"postalCode": " 122001",
					"streetAddress": "Max Super Speciality Hospital, Saket Max Super Speciality Hospital"
				 },
				"image" : "https://drarunsaroha.com/assets/img/web-3-min.png",
				"telephone": "+917860000705",
				"url": "https://drarunsaroha.com/",
				"openingHours" : ["Mo-Su 00:00-23:59"],
			"aggregateRating" : {
   "@type" : "AggregateRating",
   "ratingValue" : "4.8",
    "bestRating" : "5",
    "worstRating" : "1",
    "ratingCount" : "255"
 }
				}
			</script>
<!--<script type="application/ld+json">-->
<!--{-->
<!--  "@context" : "http://schema.org",-->
<!--  "@type" : "LocalBusiness",-->
<!--  "name" : "Dr. Arun Saroha",-->
<!--  "image" : "https://drarunsaroha.com/assets/img/web-3-min.png",-->
<!--  "description" : "With more than 20 successful years of experience in the field of Neurosurgery, Dr. Arun Saroha is an expert in treating brain & spine disorders and is the best neurosurgeon in the world.",-->
<!--  "telephone" : "917860000705",-->
<!--  "email" : "query@drarunsaroha.com",-->
<!--  "address" : {-->
<!--    "@type" : "PostalAddress",-->
<!--    "addressLocality" : "Max Super Speciality Hospital, Saket Max Super Speciality Hospital, Gurugram"-->
<!--  },-->
<!--  "url" : "https://drarunsaroha.com/",-->
<!--  "aggregateRating" : {-->
<!--    "@type" : "AggregateRating",-->
<!--    "ratingValue" : "4.8",-->
<!--    "bestRating" : "5",-->
<!--    "worstRating" : "1",-->
<!--    "ratingCount" : "255"-->
<!--  }-->
  
<!--}-->
<!--</script>-->
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Dr Arun Saroha- Best neurosurgeon in Delhi </title>
        <meta name="keywords" content="best neurosurgeon in delhi, best neurosurgeon in the world">
        <meta name="description" content="With more than 20 successful years of experience in the field of Neurosurgery, Dr. Arun Saroha is an expert in treating brain & spine disorders and is the best neurosurgeon in the world.">
         <link rel="canonical" href="https://drarunsaroha.com/" />
         <meta name="google-site-verification" content="OM26BfidiQDn4kfujdxbwcW7ehdyVH21Vde0FlApwts" />
         
        <!--start-header-->
        <?php include 'header.php';?>
        <!----End--header----->
    
   <!-- Home Slider -->
        <div class="home-slider home-slider-two owl-theme owl-carousel">
            <div class="slider-item slider-item-img-two">
                <div class="d-table">
                    <div class="d-table-cell">
                        <div class="container">
                            <div class="slider-text">
                                <div class="slider-shape">
                                    <img src="assets/img/home-one/5.png" alt="best neurosurgeon in the world">
                                </div>
                                <h2 class="ab" style="font-size: 45px; color:#000000">Avail the benefits<br> of minimally invasive Spinal<br> and Brain Surgeries </h2>
                                
                                <p class="ab">Visit the best Spinal or Neurosurgery treatment clinic in India.
                                    The center you can trust!
                                    Provides highest quality and state-of-art medical and surgical care.
                                    </p>
                                <div class="common-btn ab">
                                    <a href="contact.php">Get Appointment</a>
                                   
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
     <!-- End Home Slider       <div class="slider-item slider-item-img-three">
                <div class="d-table">
                    <div class="d-table-cell">
                        <div class="container">
                            <div class="slider-text">
                                <div class="slider-shape">
                                    <img src="assets/img/home-one/5.png" alt="Shape">
                                </div>
                                <h2>We Always Provide Best Services</h2>
                                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Quis ipsum suspendisse ultrices gravida.</p>
                                <div class="common-btn">
                                    <a href="appointment.html">Get Appointment</a>
                                    <a class="cmn-btn-right" href="about.html">Learn More</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="slider-item slider-item-img-four">
                <div class="d-table">
                    <div class="d-table-cell">
                        <div class="container">
                            <div class="slider-text">
                                <div class="slider-shape">
                                    <img src="assets/img/home-one/5.png" alt="Shape">
                                </div>
                                <h2>Hign Quality Medicines at Lowest Rates</h2>
                                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Quis ipsum suspendisse ultrices gravida.</p>
                                <div class="common-btn">
                                    <a href="appointment.html">Get Appointment</a>
                                    <a class="cmn-btn-right" href="about.html">Learn More</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>  -->
        </div>
       

        <!-- Emergency -->
        <div class="emergency-area">
            <div class="container">
                <div class="row emergency-bg">
                    <div class="col-sm-6 col-lg-4">
                        <div class="emergency-item">
                            <i class="icofont-ui-call"></i>
                            <div class="emergency-inner">
                                <h3>Emergency Call</h3>
                                <p>+91 7860 0007 05</p>
                                <p>+91 7860 0007 05</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-6 col-lg-4">
                        <div class="emergency-item">
                            <i class="icofont-location-pin"></i>
                            <div class="emergency-inner">
                                <h3>Location</h3>
                                <p>Max Super Speciality Hospital, Saket and Gurugram</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-6 offset-sm-3 offset-lg-0 col-lg-4">
                        <div class="emergency-item">
                            <i class="icofont-ambulance-crescent"></i>
                            <div class="emergency-inner">
                                <h3>Ambulance</h3>
                                <p>+91 7860 0007 05</p>
                                <p>+91 7860 0007 05</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- End Emergency -->

        <!-- Welcome -->
        <section class="welcome-area ptb-100">
            <div class="container-fluid p-0">
                <div class="row m-0">
                    <div class="col-lg-6 p-0">
                        <div class="welcome-item welcome-left">
                            <img src="assets/img/saroha-min.jpg" alt="image">
                            
                        </div>
                    </div>
                    <div class="col-lg-6 p-0">
                        <div class="welcome-item welcome-right">
                            <div class="section-title-two">
                                <span>About Doctor</span>
                                <h1>Dr. Arun Saroha, Top Neurosurgeon in Delhi (India)
</h1>
                            </div>
                            <p>Dr. Arun Saroha is one of India's best Neurosurgeons, having specializations in brain and spine surgeries. 
                            He has experience of more than 25 years and has performed more than 6,000 successful spinal and brain surgeries.
                            He has expertise in performing spine surgery, neuro-oncology, neurotrauma, scoliosis surgery, Stroke Cerebrovascular Surgery,
                            Pediatric brain and spine surgery, minimally invasive spine surgery, brain tumor surgery, spine fixation, and fusion surgery.</p>
                            <ul>
                                <li class="wow fadeInUp" data-wow-delay=".3s">
                                    <i class="icofont-doctor-alt"></i>
                                    <div class="welcome-inner">
                                        <h3>Education and Training</h3>
                                        <p>
                                            MBBS from RNT Medical College, Udaipur, Rajasthan, India
                                            MS (General Surgery) from RNT Medical College, Udaipur, Rajasthan, India
                                            MCh (Neurosurgery) from PGI Chandigarh, India
                                        </p>
                                    </div>
                                </li>
                                <li class="wow fadeInUp" data-wow-delay=".5s">
                                    <i class="icofont-stretcher"></i>
                                    <div class="welcome-inner">
                                        <h3>Emergency 24 hours</h3>
                                        <p>Offer the most advanced and modern treatment of conditions of the brain and spine by experts.</p>
                                    </div>
                                </li>
                                <li class="wow fadeInUp" data-wow-delay=".7s">
                                    <i class="icofont-network"></i>
                                    <div class="welcome-inner">
                                        <h3>Modern Technologey</h3>
                                        <p>We are committed to providing the highest level of professional service and personalized care using the most advanced medical technology applications.</p>
                                    </div>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!-- End Welcome -->
  <!-- Services -->
        <section class="services-area pb-70">
            <div class="container">
                <div class="section-title-two">
                    
                    <h2 style="text-align:center !important;">Services Offered</h2>
                </div>
                <div class="row">
                    <div class="col-sm-6 col-lg-4 wow fadeInUp" data-wow-delay=".3s">
                        <div>
                            <div class="d-table">
                                <div class="d-table-cell">
                                    <div class="service-front" style="text-align:center;">
                                        <img src="assets/img/discherif.png" alt="best neurosurgeon in delhi">
                                      
                                        <h3>Disc Herniation</h3>
                                        <p>Dr. Arun Saroha is an expert spine surgeon who performs minimally invasive Keyhole surgery spine for correcting  disk herniated. </p>
                                     <a href="herniated-disc-surgery-in-India.php">
                                            Read More
                                            <i class="icofont-long-arrow-right"></i>
                                        </a>
                                    </div>
                                  
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-6 col-lg-4 wow fadeInUp" data-wow-delay=".5s">
                        <div>
                            <div class="d-table">
                                <div class="d-table-cell">
                                    <div class="service-front" style="text-align:center;">
                                        <img src="assets/img/spondg.png" alt="best neurosurgeon in the world">
                                        <h3>Spondylosis</h3>
                                        <p>Dr. Arun Saroha performs the laminectomy, discectomy, and corpectomy surgery to correct cervical spondylosis or osteoarthritis.</p>
                                    <a href="best-treatment-cervical-spondylosis-in-India.php">
                                            Read More
                                            <i class="icofont-long-arrow-right"></i>
                                        </a>
                                    </div>
                                   
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-6 col-lg-4 wow fadeInUp" data-wow-delay=".7s">
                        <div>
                            <div class="d-table">
                                <div class="d-table-cell">
                                    <div class="service-front" style="text-align:center;">
                                        <img src="assets/img/degerativ.png" alt="best neurosurgeon in delhi">
                                        <h3>Degenerative Disc</h3>
                                        <p>Dr. Arun Saroha is an expert in performing traditional decompression surgeries  from the back and front of the spine.</p>
                                    <a href="degenerative-disc-disease-treatment-in-India.php">
                                            Read More
                                            <i class="icofont-long-arrow-right"></i>
                                        </a>
                                    </div>
                                   
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-6 col-lg-4 wow fadeInUp" data-wow-delay=".9s">
                        <div>
                            <div class="d-table">
                                <div class="d-table-cell">
                                    <div class="service-front" style="text-align:center;">
                                        <img src="assets/img/brauintum.png" alt="best neurosurgeon in the world">
                                        <h3>Brain Tumor Surgery</h3>
                                        <p>The best doctor for brain tumor removal uses the state-of-the-art equipment at the facility that makes the process of brain tumor removal easier.</p>
                                    <a href="brаіn-tumоr-surgery-in-india.php">
                                            Read More
                                            <i class="icofont-long-arrow-right"></i>
                                        </a>
                                    </div>
                                   
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-6 col-lg-4 wow fadeInUp" data-wow-delay=".3s">
                        <div>
                            <div class="d-table">
                                <div class="d-table-cell">
                                    <div class="service-front" style="text-align:center;">
                                        <img src="assets/img/brainsurg.png" alt="best neurosurgeon in delhi">
                                        <h3>Brain Surgery</h3>
                                        <p>Dr. Arun Saroha is an expert in performing a craniotomy,deep brain stimulation, and minimally invasive endonasal endoscopic surgery.</p>
                                    <a href="brain-surgery-in-India.php">
                                            Read More
                                            <i class="icofont-long-arrow-right"></i>
                                        </a>
                                    </div>
                                   
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-6 col-lg-4 wow fadeInUp" data-wow-delay=".5s">
                        <div>
                            <div class="d-table">
                                <div class="d-table-cell">
                                    <div class="service-front" style="text-align:center;">
                                        <img src="assets/img/headach.png" alt="best neurosurgeon in the world">
                                        <h3>Headache Treatment</h3>
                                        <p>Dr. Arun Saroha is an expert brain surgery doctor and provides treatment for primary, secondary, cluster, rebound, and thunderclap headaches.</p>
                                    <a href="best-headache-treatment-in-India.php">
                                            Read More
                                            <i class="icofont-long-arrow-right"></i>
                                        </a>
                                    </div>
                                   
                                </div>
                            </div>
                        </div>
                    </div>
                    
                </div>
            </div>
        </section>
        <!-- End Services -->

        <!-- Speciality -->
        <section class="speciality-area pb-100">
            <div class="container-fluid p-0">
                <div class="row m-0">
                    <div class="col-lg-7">
                        <div class="speciality-left">
                            <div class="section-title-two">
                                
                                <h2 style="text-align:center;">Why choose us?</h2>
                            </div>
                            <div class="speciality-item">
                                <div class="row m-0">
                                    <div class="col-sm-6 col-lg-6 wow fadeInUp" data-wow-delay=".3s">
                                        <div class="speciality-inner">
                                            <i class="icofont-check-circled"></i>
                                            <h3>Highest patient satisfactory rate.</h3>
                                          </div>
                                    </div>
                                    <div class="col-sm-6 col-lg-6 wow fadeInUp" data-wow-delay=".5s">
                                        <div class="speciality-inner">
                                            <i class="icofont-check-circled"></i>
                                            <h3>Safe and effective results.</h3>
                                            
                                        </div>
                                    </div>
                                    <div class="col-sm-6 col-lg-6 wow fadeInUp" data-wow-delay=".3s">
                                        <div class="speciality-inner">
                                            <i class="icofont-check-circled"></i>
                                            <h3>Patient safety priority.</h3>
                                            
                                        </div>
                                    </div>
                                    <div class="col-sm-6 col-lg-6 wow fadeInUp" data-wow-delay=".5s">
                                        <div class="speciality-inner">
                                            <i class="icofont-check-circled"></i>
                                            <h3>Sanitized rooms and fully equipped rooms.</h3>
                                            
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-5 pr-0">
                        <div class="speciality-item speciality-right">
                            <img src="assets/img/sarunstes-min.png" alt="best neurosurgeon in the world">
                         <!--   <div class="speciality-emergency">
                                <div class="speciality-icon">
                                    <i class="icofont-ui-call"></i>
                                </div>
                                <h3>Emergency Call</h3>
                                <p>+07 554 332 322</p>
                            </div> --->
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!-- End Speciality -->
        
                <div class="counter-area counter-area-two " style="background-color:#f8fbff;">
            <div class="container">
                <div class="row counter-bg">
                    <div class="col-sm-6 col-lg-3">
                        <div class="counter-item">
                            <i class="icofont-patient-bed"></i>
                            <h3 class="counter">850</h3>
                            <p>Gold Standard Treatment</p>
                        </div>
                    </div>
                    <div class="col-sm-6 col-lg-3">
                        <div class="counter-item">
                            <i class="icofont-people"></i>
                            <h3><span class="counter">6,000</span>+</h3>
                            <p>Success Brain and Spine surgeries performed</p>
                        </div>
                    </div>
                    <div class="col-sm-6 col-lg-3">
                        <div class="counter-item">
                            <i class="icofont-doctor-alt"></i>
                            <h3 class="counter">100</h3>
                            <p>Patient satisfaction Rate</p>
                        </div>
                    </div>
                    <div class="col-sm-6 col-lg-3">
                        <div class="counter-item">
                            <i class="icofont-badge"></i>
                            <h3 class="counter">25</h3>
                            <p>Years of Experience</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- End Blog -->
        
        
      
        <!-- Video -->
        <div class="video-wrap video-wrap-two">
            <div class="container-fluid p-0">
                <div class="tab-content" id="pills-tabContent">
                    <div class="tab-pane fade show active" id="pills-home" role="tabpanel" aria-labelledby="pills-home-tab">
                        <div class="video-area bra">
                            <div class="d-table">
                                <div class="d-table-cell">
                                    <div class="container">
                                        <div class="video-item">
                                            <a href="https://www.youtube.com/watch?v=50shqdODSmQ" class="popup-youtube">
                                                <i class="icofont-ui-play"></i>
                                            </a>
                                            <div class="video-content">
                                                <h3>Brain Tumour Surgery</h3>
                                                <p>The patient who Dr. Arun Saroha After getting to know about his outstanding expertise in spine and brain tumors The patient was unable to move his right side of the body and was in an unconscious state when he reached us on performing the MRI it was diagnosed a widespread grade II Tumor coming out of the skull. </p>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="tab-pane fade" id="pills-profile" role="tabpanel" aria-labelledby="pills-profile-tab">
                        <div class="video-area verte">
                            <div class="d-table">
                                <div class="d-table-cell">
                                    <div class="container">
                                        <div class="video-item">
                                            <a href="https://www.youtube.com/watch?v=oJTK69ZK4Nc" class="popup-youtube">
                                                <i class="icofont-ui-play"></i>
                                            </a>
                                            <div class="video-content">
                                                <h3>Vertebral metastasis</h3>
                                                <p>A 60 years old woman from Sudan is an operated case of D11- D12 vertebral metastasis with unknown primary post D9- L1 posterolateral fixation. She came to Dr. Arun Saroha for her spine surgery. Today, she is living her life to the fullest with her family thanks to her successful spine surgery! 
 </p>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="tab-pane fade" id="pills-contact" role="tabpanel" aria-labelledby="pills-contact-tab">
                        <div class="video-area heri">
                            <div class="d-table">
                                <div class="d-table-cell">
                                    <div class="container">
                                        <div class="video-item">
                                            <a href="https://www.youtube.com/watch?v=4DRPPrIKCrc" class="popup-youtube">
                                                <i class="icofont-ui-play"></i>
                                            </a>
                                            <div class="video-content">
                                                <h3>Herniated Disc  </h3>
                                                <p>Sher Mohammad has been a herniated disc patient for 25 years of his life. After trying every possible doctor, he finally decided to visit Dr Arun Saroha at Max Hospital, Saket, Delhi. In the video, he talks about his experience with Dr Saroha.</p>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="tab-pane fade" id="pills-icu" role="tabpanel" aria-labelledby="pills-icu-tab">
                        <div class="video-area micro">
                            <div class="d-table">
                                <div class="d-table-cell">
                                    <div class="container">
                                        <div class="video-item">
                                            <a href="https://www.youtube.com/watch?v=6XJXXva_AD8" class="popup-youtube">
                                                <i class="icofont-ui-play"></i>
                                            </a>
                                            <div class="video-content">
                                                <h3>Microscopic Spine Surgery </h3>
                                                <p>Mrs. Nada Nasrula from Iraq came to us with severe pain in the neck and back not knowing what exactly was wrong with her until she consulted Dr. Arun Saroha – Director of Neurosurgery, Max Hospital.  </p>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="tab-pane fade" id="pills-doctor" role="tabpanel" aria-labelledby="pills-doctor-tab">
                        <div class="video-area brach">
                            <div class="d-table">
                                <div class="d-table-cell">
                                    <div class="container">
                                        <div class="video-item">
                                            <a href="https://www.youtube.com/watch?v=UAB79mar3xI" class="popup-youtube">
                                                <i class="icofont-ui-play"></i>
                                            </a>
                                            <div class="video-content">
                                                <h3>Brachial plexus injury</h3>
                                                <p>Meet a Happy Patient from Kenya, Mr. Kennedy Omondi. He had an accident in 2018 where his left arm got paralyzed. He was diagnosed with left brachial plexus injury- nerve root avulsion. </p>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
    
            <div class="container">
                <ul class="video-nav nav nav-pills" id="pills-tab" role="tablist">
                    <li class="nav-item video-nav-item">
                        <a class="nav-link active" id="pills-home-tab" data-toggle="pill" href="#pills-home" role="tab" aria-controls="pills-home" aria-selected="true">Brain Tumour Surgery</a>
                    </li>
                    <li class="nav-item video-nav-item">
                        <a class="nav-link" id="pills-profile-tab" data-toggle="pill" href="#pills-profile" role="tab" aria-controls="pills-profile" aria-selected="false">vertebral metastasis</a>
                    </li>
                    <li class="nav-item video-nav-item">
                        <a class="nav-link" id="pills-contact-tab" data-toggle="pill" href="#pills-contact" role="tab" aria-controls="pills-contact" aria-selected="false">Herniated Disc</a>
                    </li>
        
                    <li class="nav-item video-nav-item">
                        <a class="nav-link" id="pills-icu-tab" data-toggle="pill" href="#pills-icu" role="tab" aria-controls="pills-icu" aria-selected="false">Microscopic Spine Surgery</a>
                    </li>
                    <li class="nav-item video-nav-item">
                        <a class="nav-link" id="pills-doctor-tab" data-toggle="pill" href="#pills-doctor" role="tab" aria-controls="pills-doctor" aria-selected="false">brachial plexus injury</a>
                    </li>
                </ul>
            </div>
        </div>
        <!-- End Video -->

        <!-- 
        <section class="doctors-area pt-100">
            <div class="container">
                <div class="section-title-two">
                    <span>Doctors</span>
                    <h2>Meet Our Doctors </h2>
                </div>
                <div class="row">
                    <div class="col-sm-6 col-lg-4 wow fadeInUp" data-wow-delay=".3s">
                        <div class="doctor-item">
                            <div class="doctor-top">
                                <img src="assets/img/home-one/doctor/1.jpg" alt="Doctor">
                                <a href="appointment.html">Get Appointment</a>
                            </div>
                            <div class="doctor-bottom">
                                <h3>
                                    <a href="doctor-details.html">Dr. Babatunde</a>
                                </h3>
                                <span>Neurosurgeon</span>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-6 col-lg-4 wow fadeInUp" data-wow-delay=".5s">
                        <div class="doctor-item">
                            <div class="doctor-top">
                                <img src="assets/img/home-one/doctor/2.jpg" alt="Doctor">
                                <a href="appointment.html">Get Appointment</a>
                            </div>
                            <div class="doctor-bottom">
                                <h3>
                                    <a href="doctor-details.html">Dr. Addision Smith</a>
                                </h3>
                                <span>Neurosurgeon</span>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-6 offset-sm-3 offset-lg-0 col-lg-4 wow fadeInUp" data-wow-delay=".7s">
                        <div class="doctor-item">
                            <div class="doctor-top">
                                <img src="assets/img/home-one/doctor/3.jpg" alt="Doctor">
                                <a href="appointment.html">Get Appointment</a>
                            </div>
                            <div class="doctor-bottom">
                                <h3>
                                    <a href="doctor-details.html">Dr. Sarah Tylor</a>
                                </h3>
                                <span>Dental Surgeon</span>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="doctor-btn">
                    <a href="doctor.html">See All</a>
                </div>
            </div>
        </section>
        <!-- End Doctors -->

        <!-- Counter -->
        
        <!-- End Counter -->

        <!-- 
        <section class="appointment-area pb-100">
            <div class="container-fluid p-0">
                <div class="appointment-item">
                    <h2>Book your appointment</h2>
                    <span>We will confirm your  appointment within 2 hours</span>
                    <div class="appointment-form">
                        <form>
                            <div class="row">
                                <div class="col-lg-6">
                                    <div class="form-group">
                                        <i class="icofont-business-man-alt-1"></i>
                                        <label>Name</label>
                                        <input type="text" class="form-control" placeholder="Enter Your Name">
                                    </div>
                                </div>
                                <div class="col-lg-6">
                                    <div class="form-group">
                                        <i class="icofont-ui-message"></i>
                                        <label>Email</label>
                                        <input type="email" class="form-control" placeholder="Enter Your Email">
                                    </div>
                                </div>
                                <div class="col-lg-6">
                                    <div class="form-group">
                                        <i class="icofont-ui-call"></i>
                                        <label>Phone</label>
                                        <input type="text" class="form-control" placeholder="Enter Your Number">
                                    </div>
                                </div>
                                <div class="col-lg-6">
                                    <div class="form-group">
                                        <i class="icofont-hospital"></i>
                                        <label>Services</label>
                                        <select class="form-control" id="exampleFormControlSelect1">
                                            <option>Dental Care</option>
                                            <option>Neurology</option>
                                            <option>Cardiology</option>
                                            <option>Pathology</option>
                                        </select>
                                    </div>
                                </div>
                                
                            </div>
                            <div class="text-center">
                                <button type="submit" class="btn appointment-btn">Submit</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </section>
        <!-- End Appointment -->

        <!-- Blog -->
        <section class="blog-area pt-100 pb-70">
            <div class="container">
                <div class="section-title-two">
                    
                    <h2 style="text-align:center;">Our Latest Blogs</h2>
                </div>
                <div class="row">
                    <div class="col-sm-6 col-lg-4 wow fadeInUp" data-wow-delay=".3s">
                        <div class="blog-item">
                            <div class="blog-top">
                                <a href="#">
                                    <img src="assets/img/disk replacement-min.jpg" alt="best neurosurgeon in the world">
                                </a>
                            </div>
                            <div class="blog-bottom">
                                <h3>
                                    <a href="#">Disk Replacement</a>
                                </h3>
                                <p>Health is what we make of it!<br>
                                      The least prioritized goals that we have, and sometimes it is not even part of the list is how is our body managing it all!...
                                </p>
                                <ul>
                                    <li>
                                        <a href="#">
                                            Read More
                                            <i class="icofont-long-arrow-right"></i>
                                        </a>
                                    </li>
                                    <li>
                                        <i class="icofont-calendar"></i>
                                        Jan 03, 2020
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-6 col-lg-4 wow fadeInUp" data-wow-delay=".5s">
                        <div class="blog-item">
                            <div class="blog-top">
                                <a href="#">
                                    <img src="assets/img/brain-surgery-min.jpg" alt="best neurosurgeon in delhi">
                                </a>
                            </div>
                            <div class="blog-bottom">
                                <h3>
                                    <a href="#">Benefits of Having Brain Surgery in India</a>
                                </h3>
                                <p>The brain is the most important part of the body that controls most of the movement and function of our body....</p>
                                <ul>
                                    <li>
                                        <a href="#">
                                            Read More
                                            <i class="icofont-long-arrow-right"></i>
                                        </a>
                                    </li>
                                    <li>
                                        <i class="icofont-calendar"></i>
                                        Jan 03, 2020
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-6 offset-sm-3 offset-lg-0 col-lg-4 wow fadeInUp" data-wow-delay=".7s">
                        <div class="blog-item">
                            <div class="blog-top">
                                <a href="#">
                                    <img src="assets/img/invasive spine surgery-min.jpg" alt="best neurosurgeon in delhi">
                                </a>
                            </div>
                            <div class="blog-bottom">
                                <h3>
                                    <a href="#">Future Belongs To Minimally Invasive Spine Surgery</a>
                                </h3>
                                <p>Minimally invasive spine surgery is another name for what we know as a keyhole surgery...</p>
                                <ul>
                                    <li>
                                        <a href="#">
                                            Read More
                                            <i class="icofont-long-arrow-right"></i>
                                        </a>
                                    </li>
                                    <li>
                                        <i class="icofont-calendar"></i>
                                        Jan 03, 2020
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!--<div class="counter-area counter-area-two">-->
        <!--    <div class="container">-->
        <!--        <div class="row counter-bg">-->
        <!--            <div class="col-sm-6 col-lg-3">-->
        <!--                <div class="counter-item">-->
        <!--                    <i class="icofont-patient-bed"></i>-->
        <!--                    <h3 class="counter">850</h3>-->
        <!--                    <p>Gold Standard Treatment</p>-->
        <!--                </div>-->
        <!--            </div>-->
        <!--            <div class="col-sm-6 col-lg-3">-->
        <!--                <div class="counter-item">-->
        <!--                    <i class="icofont-people"></i>-->
        <!--                    <h3><span class="counter">6,000</span>+</h3>-->
        <!--                    <p>Success Brain and Spine surgeries performed</p>-->
        <!--                </div>-->
        <!--            </div>-->
        <!--            <div class="col-sm-6 col-lg-3">-->
        <!--                <div class="counter-item">-->
        <!--                    <i class="icofont-doctor-alt"></i>-->
        <!--                    <h3 class="counter">100</h3>-->
        <!--                    <p>Patient satisfaction Rate</p>-->
        <!--                </div>-->
        <!--            </div>-->
        <!--            <div class="col-sm-6 col-lg-3">-->
        <!--                <div class="counter-item">-->
        <!--                    <i class="icofont-badge"></i>-->
        <!--                    <h3 class="counter">25</h3>-->
        <!--                    <p>Years of Experience</p>-->
        <!--                </div>-->
        <!--            </div>-->
        <!--        </div>-->
        <!--    </div>-->
        <!--</div>-->
        <!-- End Blog -->

        <!-- Footer -->

       <?php include 'footer.php';?>

