<!DOCTYPE html>
<html hreflang="en">
<head>
  <!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
  <script type="application/ld+json">
				{
				   "@context" : "http://schema.org",
				   "@type" : "Hospital",
				   "name": "Dr. Arun Saroha: Best Neurosurgeon in India ",  
				   "address": {
					"@type": "PostalAddress",
					"addressLocality": "Haryana,India",
					"addressRegion": "Gurugram",
					"postalCode": " 122001",
					"streetAddress": "Max Super Speciality Hospital, Saket Max Super Speciality Hospital"
				 },
				"image" : "https://drarunsaroha.com/assets/img/web-3-min.png",
				"telephone": "+917860000705",
				"url": "https://drarunsaroha.com/",
				"openingHours" : ["Mo-Su 00:00-23:59"],
			"aggregateRating" : {
   "@type" : "AggregateRating",
   "ratingValue" : "4.8",
    "bestRating" : "5",
    "worstRating" : "1",
    "ratingCount" : "255"
        }
			}
			</script>
  <!-- Global site tag (gtag.js) - Google Analytics -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=UA-224697704-1"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag() { dataLayer.push(arguments); }
    gtag('js', new Date());
    gtag('config', 'UA-224697704-1');
  </script>
  
   <style>
     .qb-banner{
         display:none;
     }
     .qb-full .qb-post-image{
         text-align:left;
         width:auto;
     }
     .qb-three-column #qb-three {
        min-height: 520px;
        height:520px
     }
     .qb-content h1{
         margin-top:10px;
     }
 </style>
  
  <!--<script type="application/ld+json">-->
  <!--{-->
  <!--  "@context" : "http://schema.org",-->
  <!--  "@type" : "LocalBusiness",-->
  <!--  "name" : "Dr. Arun Saroha",-->
  <!--  "image" : "https://drarunsaroha.com/assets/img/web-3-min.png",-->
  <!--  "description" : "With more than 20 successful years of experience in the field of Neurosurgery, Dr. Arun Saroha is an expert in treating brain & spine disorders and is the best neurosurgeon in the world.",-->
  <!--  "telephone" : "917860000705",-->
  <!--  "email" : "query@drarunsaroha.com",-->
  <!--  "address" : {-->
  <!--    "@type" : "PostalAddress",-->
  <!--    "addressLocality" : "Max Super Speciality Hospital, Saket Max Super Speciality Hospital, Gurugram"-->
  <!--  },-->
  <!--  "url" : "https://drarunsaroha.com/",-->
  <!--  "aggregateRating" : {-->
  <!--    "@type" : "AggregateRating",-->
  <!--    "ratingValue" : "4.8",-->
  <!--    "bestRating" : "5",-->
  <!--    "worstRating" : "1",-->
  <!--    "ratingCount" : "255"-->
  <!--  }-->
  <!--}-->
  <!--</script>-->
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Dr. Arun Saroha: Best Neurosurgeon & Spine Surgeon in India |</title>
  <meta name="description"
    content="Dr. Arun Saroha is the most trusted & recommended neurosurgeon & spine surgeon in India who specializes in brain and spine procedures. Schedule an appointment with him if you are searching for the best neurosurgeon in India. ">
  <link rel="canonical" href="https://drarunsaroha.com/" />
  <meta name="google-site-verification" content="OM26BfidiQDn4kfujdxbwcW7ehdyVH21Vde0FlApwts" />
  <!--start-header-->
  <?php include 'header.php';?>
  <script src="https://app.quickblog.co/js/embed.js?qb_id=2453z7R6vpqBgxxGuMUPqycyyFLssqdC2LDJW2mtTaMj"></script>
  <!----End--header----->
  <!-- Home Slider -->
  <section>
      <div class="container">
          <div class="row">
               <div id="qb-posts"></div> 
          </div>
      </div>
  </section>
 

  <?php include 'footer.php';?>